# Exercise 5.A NumPy fundamentals
## Array Basics

In [18]:
import numpy as np
fruits = ["apple", "banana", "cherry", "date"]

In [19]:
arr_1 = np.array(fruits)
print(fruits)
print(arr_1.dtype) # U is unicode(str/text) and 6 is the length of the longest string in the the list

['apple', 'banana', 'cherry', 'date']
<U6


In [20]:
arr_2 = np.array([(10, 11, 12), 
                  (13, 14, 15)])
print(arr_2)
print((arr_2.T)) # the transposed version switches the places of rows and columns

[[10 11 12]
 [13 14 15]]
[[10 13]
 [11 14]
 [12 15]]


In [21]:
arr_3 = np.array([(1, 3, 5),
                 (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [22]:
arr_4 = np.array([arr_3[0,2], arr_3[1,1]]) # gets specific values from arr_3
print(arr_4)

[5 4]


In [23]:
arr_5 = np.ones((2,2,2)) # makes a 3 dimensional array of ones
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
