# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [6]:
arrA = np.array([[11, 12, 13],
                [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [7]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


### The first loop multiplies each row by two and the second loop prints each value separately.

In [9]:
for x in arrA:
    for y in x:
        loop_result = y * 2
        print(loop_result)

22
24
26
28
30
32


In [10]:
# The result is the same. The difference is that the multiplied value is stored in a variable before printing.

## Joining and Stacking Arrays

In [11]:
joined_array_1 = np.concatenate((arrA,  arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [12]:
joined_array_2 = np.concatenate((arrA,  arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [13]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [15]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2)) # ValueError: all input arrays must have the same shape.
                                                            # It is because the arrays don't have same shape.
print(stacked_array_2)

ValueError: all input arrays must have the same shape

In [18]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [19]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1) # The arrays have different numbers of rows. 
print(another_2)                                           # joined_array_1 has 4 rows and arrA has 2 rows.
print(another_2)                                           

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [21]:
arrAHS = np.hstack((arrA, arrA)) # it is stacking the arrays horizontaly 
print(arrAHS)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [22]:
arrAVS = np.vstack((arrA, arrA)) # it is stacking the arrays vertically
print(arrAVS)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [23]:
arrADS = np.dstack((arrA, arrA)) # it is stacking the arrays depth-wise
print(arrADS)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [26]:
splitsky = np.split(joined_array_1, 2) # it has 2 arrays with two dimensions each. 
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [28]:
spliterino = np.array_split(joined_array_1, 3) # it has 2 dimensional arrays. The first array has two rows
print(spliterino                               # and the rest have one row each because 4 can't be divided evenly into 3.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [29]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [30]:
arrB = (((7,6), (13,5), (7,3)))
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [34]:
arrB = np.array(((7,6), (13,5), (7,3)))
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [35]:
arrB = np.array(((7,6), (13,5), (7,3)))
print(arrB)
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
