# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [ ]:
r_1 = np.random.randint(1, 20, 2) # randint to generate integers
print(r_1)                        # specifies the row

[13 12]


In [ ]:
r_2 = np.random.randint(1, 20, (1, 2)) # randint to generate integer
print(r_2)                             # specifies rows and columns

[[ 7 16]]


In [ ]:
r_3 = np.random.rand(2, 1) # rand to generate float
print(r_3)                 # specifies 2 rows and 1 column

[[0.15916344]
 [0.36295699]]


In [13]:
r_4 = np.random.randint(20, 100, (4, 5)) # random integers between 
print(r_4)                               # 20, 100 and 4 rows and 5 colums 

[[53 55 54 88 61]
 [52 43 79 45 65]
 [98 69 63 22 77]
 [40 31 33 91 93]]


In [15]:
r_5 = np.random.rand(4, 5) # floats, 4 rows and 5 colums
print(r_5)

[[0.78414078 0.6862207  0.12430682 0.62306647 0.61697157]
 [0.86929154 0.49235748 0.15954666 0.03074509 0.768116  ]
 [0.68338781 0.19885754 0.19165377 0.1066438  0.31474429]
 [0.43033805 0.78608647 0.69960177 0.68261637 0.83364421]]


 ## Generating Random Choices from an Array

In [18]:
students = np.array([
    "Alexus", "Alondra", "Betelehem", "Blake", 
    "Charles", "Corey", "Dagmawi", "Danait",
    "Daniel", "Hana", "Lesley", "Lorah"
])
print(students)

['Alexus' 'Alondra' 'Betelehem' 'Blake' 'Charles' 'Corey' 'Dagmawi'
 'Danait' 'Daniel' 'Hana' 'Lesley' 'Lorah']


In [19]:
call_on = np.random.choice(students)
print(call_on)

Corey


In [24]:
breakout_groups = np.random.choice(students, (3, 4))
print(breakout_groups) # It wouldn't be an effective way 
                       # to assign breakout groups because 
                       # some of the names assigned more than once. 
                       

[['Hana' 'Lesley' 'Blake' 'Daniel']
 ['Danait' 'Danait' 'Alexus' 'Blake']
 ['Danait' 'Blake' 'Lesley' 'Alexus']]


In [31]:
call_on_weighted = np.random.choice(students, 5,
        p =[0.05, 0.3, 0.1, 0, 0.1, 0.05, 0.05, 0.05, 0.1, 0.05, 0.1, 0.05])
print(call_on_weighted) # Alondra has 30% probability and Blake 
                        # had 0% probability. The other students had
                        # similar probability of being selected. some 0.05 and some 0.1
                        

['Danait' 'Alondra' 'Charles' 'Alondra' 'Dagmawi']


 ## Generating a Normal Distribution

In [32]:
bell_curve = np.random.normal(10, 5, (4, 5))
print(bell_curve)

[[11.36982764  5.33292849 12.72939258 11.61470292 11.50644329]
 [ 8.41604438  2.80396361  9.51933203  6.23168314  7.10599807]
 [ 2.24109843  8.41220662 21.14948794 16.97980438  6.96243555]
 [ 5.83948834 10.79763576 12.03410953 14.77761523 15.01075071]]
