# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 20, 2)
r_2 = np.random.randint(1, 20, (1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, (4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

In [4]:
print(r_4)

[[74 75 66 68 93]
 [96 45 49 79 52]
 [67 23 98 48 22]
 [64 88 68 31 42]]


In [6]:
np.random.shuffle(r_4) # The rows are shuffled but the values inside the rows are not shuffled and it shuffles the original.
print(r_4)

[[74 75 66 68 93]
 [67 23 98 48 22]
 [64 88 68 31 42]
 [96 45 49 79 52]]


In [8]:
new_shuffle = np.random.permutation(r_4) # Permutation creats a new shuffeled copy. 
print(new_shuffle)
print(r_4)

[[67 23 98 48 22]
 [74 75 66 68 93]
 [96 45 49 79 52]
 [64 88 68 31 42]]
[[96 45 49 79 52]
 [67 23 98 48 22]
 [74 75 66 68 93]
 [64 88 68 31 42]]


I would use shuffle to randomly shuffle the original and I would use permutation when I want to keep the original as it is but shuffle a copy. 

## Mathematical Operations

In [11]:
print(r_1)
print(r_1.shape)

[ 7 15]
(2,)


In [12]:
print(r_2)
print(r_2.shape)

[[ 1 18]]
(1, 2)


In [14]:
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[[ 8 33]]
(1, 2)


In [15]:
print(r_1)
print(r_1.shape)

[ 7 15]
(2,)


In [16]:
print(r_3)
print(r_3.shape)

[[0.54362563]
 [0.99618824]]
(2, 1)


In [17]:
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[[ 7.54362563 15.54362563]
 [ 7.99618824 15.99618824]]
(2, 2)


In [18]:
print(r_2)
print(r_2.shape)

[[ 1 18]]
(1, 2)


In [19]:
print(r_4)
print(r_4.shape)

[[96 45 49 79 52]
 [67 23 98 48 22]
 [74 75 66 68 93]
 [64 88 68 31 42]]
(4, 5)


In [20]:
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [21]:
print(r_3)
print(r_3.shape)

[[0.54362563]
 [0.99618824]]
(2, 1)


In [22]:
print(r_4)
print(r_4.shape)

[[96 45 49 79 52]
 [67 23 98 48 22]
 [74 75 66 68 93]
 [64 88 68 31 42]]
(4, 5)


In [23]:
print(np.add(r_3, r_4))
print(np.add(r_3, r_4).shape)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Numpy can not add r_1, r_2 or r_3 with r_4 because they have different shape but it can add r_5 since it has similar shape.

In [25]:
print(r_4 + np.array(([1]))) # adds 1 for each value

[[97 46 50 80 53]
 [68 24 99 49 23]
 [75 76 67 69 94]
 [65 89 69 32 43]]


In [27]:
print(r_4 + np.array([[1]])) # same as above, it adds 1 to each value

[[97 46 50 80 53]
 [68 24 99 49 23]
 [75 76 67 69 94]
 [65 89 69 32 43]]


In [28]:
print(r_4 + np.array([1,1,1,1,1])) # add 1 to each value in every row

[[97 46 50 80 53]
 [68 24 99 49 23]
 [75 76 67 69 94]
 [65 89 69 32 43]]


In [29]:
print(r_4 + np.array([[1],[1]])) # gives an error because the shapes are not the compatible

ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

Based on the the expression, arrays can be added if they have compatible shapes. If the value is one, it can be streched and added everywhere. 

## Rounding

In [30]:
print(r_3)

[[0.54362563]
 [0.99618824]]


In [32]:
print(np. trunc(r_3)) # removes the decimal part
print(np. fix(r_3)) # removes the decimal part
print(np. floor(r_3)) # rounds down
print(np. ceil(r_3)) # rounds up
print(np. round(r_3, 2)) # 2 numbers after the decimal

[[0.]
 [0.]]
[[0.]
 [0.]]
[[0.]
 [0.]]
[[1.]
 [1.]]
[[0.54]
 [1.  ]]


## Cumulative Operations

In [33]:
print(r_4)

[[96 45 49 79 52]
 [67 23 98 48 22]
 [74 75 66 68 93]
 [64 88 68 31 42]]


In [34]:
print(np.sum(r_4)) # sum of all the values

1248


In [39]:
print(np.sum(r_4, axis=0)) # adds across the columns

[301 231 281 226 209]


In [40]:
print(np.sum(r_4, axis=1)) # adds across the rows

[321 258 376 293]


In [43]:
print(np.cumsum(r_4)) # it is the rolling value

[  96  141  190  269  321  388  411  509  557  579  653  728  794  862
  955 1019 1107 1175 1206 1248]


In [44]:
print(np.cumsum(r_4, axis=0)) # cumulative sum across the columns

[[ 96  45  49  79  52]
 [163  68 147 127  74]
 [237 143 213 195 167]
 [301 231 281 226 209]]


## Grocery Problem


In [45]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [47]:
print("The first bag contains", np.sum(bag1), "items.")
print("The second bag contains", np.sum(bag2), "items.")

The first bag contains 9 items.
The second bag contains 7 items.


In [50]:
total = bag1 + bag2
print("There are", total[0], "vegetables,", total[1], "fruits,", total[2], 
      "boxes of snacks, and", total[3], "beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


 ## Teamwork

In [51]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])


In [52]:
print(ali)
print(ben)
print(carla)

[5 4 6 4 2]
[0 5 5 3 4]
[3 6 0 3 4]


In [53]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [55]:
print(np.sum(all_knocks, axis=1)) # the total number of doors that each person knocked 

[21 17 16]


In [56]:
print(np.sum(all_knocks)) #  total number of doors that the group collectively knocked on

54


In [57]:
total_by_day = np.sum(all_knocks, axis=0) # how many days were knocked everyday
print(total_by_day)

[ 8 15 11 10 10]


In [58]:
rolling_total = np.cumsum(total_by_day) # the rolling total of knocks
print(rolling_total)

[ 8 23 34 44 54]


In [59]:
estimated_votes = rolling_total * 0.5 # *.5 because 1 vote for every 2 knocks 
print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
